# Basic site config
title           = "Virtual Kubelet"
baseURL         = "https://virtual-kubelet.netlify.com"
languageCode    = "en-us"
enableRobotsTxt = true

# Taxonomy configuration (disable taxonomies for now)
disableKinds = ["taxonomyTerm"]

# Syntax highlighting config
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle      = "monokai"

# BlackFriday Markdown settings
[blackfriday]
hrefTargetBlank = true
