# Basic site config
title           = "Virtual Kubelet"
baseURL         = "https://virtual-kubelet.netlify.com"
languageCode    = "en-us"
enableRobotsTxt = true

# Taxonomy configuration (disable taxonomies for now)
disableKinds = ["taxonomyTerm"]

# Syntax highlighting config
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle      = "monokai"

# BlackFriday Markdown settings
[blackfriday]
hrefTargetBlank = true

# General site-level parameters
[params]
sansSerifFont      = "Noto Sans TC"
#monospaceFont      = "Fira Mono"
fontAwesomeVersion = "5.5.0"
description        = """
**Virtual Kubelet** is an open-source [Kubernetes kubelet](https://kubernetes.io/docs/reference/generated/kubelet/) implementation that *masquerades* as a kubelet. 

This allows Kubernetes nodes to be backed by Virtual Kubelet **providers** such as serverless cloud container platforms.
"""

[params.social]
twitter = "https://twitter.com/virtualkubelet"
github  = "https://github.com/virtual-kubelet/virtual-kubelet"

[[params.fonts]]
name  = "Noto Sans TC"
sizes = [300,400,600,700]

#[[params.fonts]]
#name  = "Fira Mono"
#sizes = [400]
